import { CartProvider } from "@/lib/cart-context";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-white text-gray-900">
        <main className="max-w-md mx-auto p-4">
          <CartProvider>{children}</CartProvider>
        </main>
      </body>
    </html>
  );
}
